name: Sync main to main-copy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to main-copy
        run: |
          git checkout -b main-copy || git checkout main-copy
          git merge --no-ff main -m "Sync from main"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/<USERNAME>/<REPO>.git main-copy
