name: Sync main to main-copy

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # Create or update main-copy branch
      - name: Push to main-copy
        run: |
          git checkout -b main-copy || git checkout main-copy
          git merge --no-ff main -m "Sync from main"
          git push origin main-copy
